name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it
    permissions:
      contents: read

    steps:
        - uses: actions/checkout@v4
    
        - name: De-bloat stock image
          run: |
            rm -r /run/host/usr/share/dotnet
            rm -r /run/host${{ runner.tool_cache }}
    
        - name: Install needed packages
          run: apt update && apt install -y dpkg-dev build-essential debhelper plymouth plymouth-label plymouth-themes gettext meson
    
        - name: Build debian package
          run: |
            dpkg-buildpackage --no-sign
            mv ../plymouth-theme-singularity-bgrt*.deb ../plymouth-theme-singularity-bgrt.deb
            mv ../plymouth-theme-singularity-logo*.deb ../plymouth-theme-singularity-logo.deb
            mv ../plymouth-theme-singularity-text*.deb ../plymouth-theme-singularity-text.deb
    
        - name: Calculate and Save Checksums
          run: |
            sha256sum /__w/plymouth-theme-singularity/plymouth-theme-singularity-bgrt.deb >> checksums.txt
            sha256sum /__w/plymouth-theme-singularity/plymouth-theme-singularity-logo.deb >> checksums.txt
            sha256sum /__w/plymouth-theme-singularity/plymouth-theme-singularity-text.deb >> checksums.txt
      
        - uses: actions/upload-artifact@v4
          with:
            name: plymouth-theme-singularity
            path: |
                /__w/plymouth-theme-singularity/plymouth-theme-singularity-bgrt.deb
                /__w/plymouth-theme-singularity/plymouth-theme-singularity-logo.deb
                /__w/plymouth-theme-singularity/plymouth-theme-singularity-text.deb
                checksums.txt

        - uses: actions/upload-artifact@v4
          with:
            name: base-files
            path: |
                checksums.txt
                /__w/base-files/base-files.deb

  release:
    runs-on: ubuntu-latest
    needs: build-artifacts
    permissions:
      contents: write # to create and upload assets to releases
      attestations: write # to upload assets attestation for build provenance
      id-token: write # grant additional permission to attestation action to mint the OIDC token permission

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: plymouth-theme-singularity

      - name: Create Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --generate-notes *.deb plymouth-theme-singularity/checksums.txt
      
      - name: Attest Release Files
        id: attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '*.deb, plymouth-theme-singularity/*.txt'
